parameters:
    cowegis_contao_provider_layer.providers:
        OpenStreetMap:
            url: 'https://www.openstreetmap.org/copyright'
            variants:
                0: Mapnik
                1: DE
                2: CH
                France: {}
                HOT:
                    url: 'https://www.hotosm.org/'
                BZH:
                    url: 'http://www.openstreetmap.bzh/'
                CAT:
                    url: 'https://www.openstreetmap.cat/'

        OpenSeaMap:
            url: 'http://www.openseamap.org'

        OpenTopoMap:
            url: 'http://viewfinderpanoramas.org'

        OpenRailwayMap:
            url: 'http://www.OpenRailwayMap.org'

        SafeCast:
            url: 'http://blog.safecast.org/about/'

        Stadia:
            url: 'https://stadiamaps.com/'
            variants:
                - AlidadeSmooth
                - AlidadeSmoothDark
                - AlidadeSatellite
                - OSMBright
                - Outdoors
                - StamenToner
                - StamenTonerBackground
                - StamenTonerLines
                - StamenTonerLabels
                - StamenTonerLite
                - StamenTonerDark
                - StamenTonerBlacklite
                - StamenWatercolor
                - StamenTerrain
                - StamenTerrainBackground
                - StamenTerrainLabels
                - StamenTerrainLines

        Thunderforest:
            url: 'https://www.thunderforest.com/'
            variants:
                - OpenCycleMap
                - Transport
                - TransportDark
                - SpinalMap
                - Landscape
                - Outdoors
                - Pioneer
                - MobileAtlas
                - Neighbourhood
                - Atlas
            options:
                apikey: tile_provider_key
            fields:
                - tile_provider_key

        CyclOSM:
            url: 'https://github.com/cyclosm/cyclosm-cartocss-style'

        Jawg:
            url: 'https://www.jawg.io/lab/'
            variants:
                - Streets
                - Terrain
                - Lagoon
                - Sunny
                - Dark
                - Light
                - Matrix

        MapBox:
            url: 'https://www.mapbox.com'
            options:
                accessToken: tile_provider_key
            fields:
                - tile_provider_key

        MapTiler:
            url: 'https://www.maptiler.com/copyright'
            variants:
                - Streets
                - Basic
                - Bright
                - Pastel
                - Positron
                - Hybrid
                - Toner
                - Topo
                - Voyager
                - Ocean
                - Backdrop
                - Dataviz
                - DatavizLight
                - DatavizDark
                - Aquarelle
                - Landscape
                - Openstreetmap
                - Outdoor
                - Satellite
                - Winter
            options:
                key: tile_provider_key
            fields:
                - tile_provider_key

        TomTom:
            url: 'https://tomtom.com'
            variants:
                - Basic
                - Hybrid
                - Labels
            options:
                apikey: tile_provider_key
            fields:
                - tile_provider_key

        Esri:
            url: 'https://arcgisonline.com'
            variants:
                - WorldStreetMap
                - WorldTopoMap
                - WorldImagery
                - WorldTerrain
                - WorldShadedRelief
                - WorldPhysical
                - OceanBasemap
                - NatGeoWorldMap
                - WorldGrayCanvas

        OpenWeatherMap:
            url: 'https://openweathermap.org'
            variants:
                - Clouds
                - CloudsClassic
                - Precipitation
                - PrecipitationClassic
                - Rain
                - RainClassic
                - Pressure
                - PressureContour
                - Wind
                - Temperature
                - Snow
            options:
                apiKey: tile_provider_key
            fields:
                - tile_provider_key

        HERE:
            url: 'https://platform.here.com'
            variants:
                - exploreDay
                - liteDay
                - logisticsDay
                - topoDay
                - logisticsNight
                - exploreNight
                - topoNight
                - liteNight
                - exploreSatelliteDay
                - liteSatelliteDay
                - logisticsSatelliteDay
                - basicMap
                - mapLabels
                - trafficFlow
                - carnavDayGrey
                - hybridDay
                - hybridDayMobile
                - hybridDayTransit
                - hybridDayGrey
                - pedestrianDay
                - pedestrianNight
                - satelliteDay
                - terrainDay
                - terrainDayMobile
            options:
                apiKey: tile_provider_key
            fields:
                - tile_provider_key

        FreeMapSK:
            url: 'https://www.freemap.sk/'

        MtbMap:
            url: 'http://mtbmap.cz/'

        CartoDB:
            url: 'https://carto.com/attributions'
            variants:
                - Positron
                - PositronNoLabels
                - PositronOnlyLabels
                - DarkMatter
                - DarkMatterNoLabels
                - DarkMatterOnlyLabels
                - Voyager
                - VoyagerNoLabels
                - VoyagerOnlyLabels
                - VoyagerLabelsUnder

        HikeBike:
            url: 'https://wmflabs.org'
            variants:
                - HikeBike
                - HillShading

        BasemapAT:
            url: 'https://www.basemap.at'
            variants:
                - basemap
                - grau
                - overlay
                - terrain
                - surface
                - highdpi
                - orthofoto

        nlmaps:
            url: 'https://www.kadaster.nl/'
            variants:
                - standaard
                - pastel
                - grijs
                - water
                - luchtfoto

        NASAGIBS:
            url: 'https://earthdata.nasa.gov'
            variants:
                - ModisTerraTrueColorCR
                - ModisTerraBands367CR
                - ViirsEarthAtNight2012
                - ModisTerraLSTDay
                - ModisTerraSnowCover
                - ModisTerraAOD
                - ModisTerraChlorophyll

        NLS:
            url: 'http://maps.nls.uk/projects/subscription-api'
            variants:
                - osgb63k1885
                - osgb1888
                - osgb10k1888
                - osgb1919
                - osgb25k1937
                - osgb63k1955
                - oslondon1k1893
            options:
                apikey: tile_provider_key
            fields:
                - tile_provider_key

        JusticeMap:
            url: 'http://www.justicemap.org/terms.php'
            variants:
                - income
                - americanIndian
                - asian
                - black
                - hispanic
                - multi
                - nonWhite
                - white
                - plurality

        GeoportailFrance:
            url: 'https://www.geoportail.gouv.fr/'
            variants:
                - plan
                - parcels
                - orthos

        OneMapSG:
            url: 'https://www.sla.gov.sg/'
            variants:
                - Default
                - Night
                - Original
                - Grey
                - LandLot

        MapTilesAPI:
            url: 'http://www.maptilesapi.com/'
            variants:
                - OSMEnglish
                - OSMFrancais
                - OSMEspagnol
            options:
                apikey: tile_provider_key
            fields:
                - tile_provider_key

        OPNVKarte:
            url: 'https://memomaps.de/'

        BaseMapDE:
            url: 'http://www.govdata.de/dl-de/by-2-0'
            variants:
                - Color
                - Grey

        USGS:
            url: 'https://www.usgs.gov/'
            variants:
                - USTopo
                - USImagery
                - USImageryTopo

        WaymarkedTrails:
            url: 'https://waymarkedtrails.org'
            variants:
                - hiking
                - cycling
                - mtb
                - slopes
                - riding
                - skating

        OpenAIP:
            url: 'https://www.openaip.net/'

        OpenSnowMap:
            url: 'https://www.opensnowmap.org/iframes/data.html'
            variants:
                - pistes

        AzureMaps:
            url: 'https://docs.microsoft.com/en-us/rest/api/maps/render-v2/get-map-tile'
            variants:
                - MicrosoftImagery
                - MicrosoftBaseDarkGrey
                - MicrosoftBaseRoad
                - MicrosoftBaseHybridRoad
                - MicrosoftTerraMain
                - MicrosoftWeatherInfraredMain
                - MicrosoftWeatherRadarMain
            options:
                subscriptionKey: tile_provider_key
            fields:
                - tile_provider_key

        SwissFederalGeoportal:
            url: 'https://www.swisstopo.admin.ch/'
            variants:
                - NationalMapColor
                - NationalMapGrey
                - SWISSIMAGE

        TopPlusOpen:
            url: 'http://www.govdata.de/dl-de/by-2-0'
            variants:
                - Color
                - Grey
